### ISSUE TITLE
エラー An error occurred during route handling or page rendering.

### ISSUE THREAD

**Issue by wilf312** [wilf312/voicecamp#54]
```
An error occurred during route handling or page rendering.

Error: Objects are not valid as a child. Encountered an object with the keys {0,1,2,3,4,5,6}.

  in a
  in Menu
  in 
  in GreetPage
  in Component
  in App

    at https://esm.sh/stable/preact@10.10.0/denonext/debug.js:38:974
    at Array.forEach (<anonymous>)
    at i.diffed (https://esm.sh/stable/preact@10.10.0/denonext/debug.js:38:869)
    at k (https://esm.sh/v133/preact-render-to-string@6.1.0/X-ZS9wcmVhY3Q/denonext/preact-render-to-string.mjs:2:3699)
    at k (https://esm.sh/v133/preact-render-to-string@6.1.0/X-ZS9wcmVhY3Q/denonext/preact-render-to-string.mjs:2:2018)
    at k (https://esm.sh/v133/preact-render-to-string@6.1.0/X-ZS9wcmVhY3Q/denonext/preact-render-to-string.mjs:2:3649)
    at k (https://esm.sh/v133/preact-render-to-string@6.1.0/X-ZS9wcmVhY3Q/denonext/preact-render-to-string.mjs:2:2591)
    at k (https://esm.sh/v133/preact-render-to-string@6.1.0/X-ZS9wcmVhY3Q/denonext/preact-render-to-string.mjs:2:2018)
    at k (https://esm.sh/v133/preact-render-to-string@6.1.0/X-ZS9wcmVhY3Q/denonext/preact-render-to-string.mjs:2:2591)
    at k (https://esm.sh/v133/preact-render-to-string@6.1.0/X-ZS9wcmVhY3Q/denonext/preact-render-to-string.mjs:2:3649)
```

**Comment by wilf312** [comment]
#55 

https://github.com/wilf312/voicecamp/pull/55/files#diff-92d6086f7630dd58a9bf2713de3849ccde8ce4bf11d6cce8278f34c071bcad82L3 のアップデートで解消した
